### ISSUE TITLE
docker-compose postgres error

### ISSUE THREAD

**Issue by Tarik-H** [afourmy/eNMS#157]
Hi,
I cloned eNMS repo and trying to use docker-compose but getting postgress errors about field type error for device_name and current_configuration: sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) type modifier is not allowed for type "text"  LINE 17:  current_configuration TEXT(32768), 
I'm using the default docker-compose:

```
version: "3"
services:
  db:
    restart: always
    image: postgres:latest
    environment:
     - POSTGRES_USER=enms
     - POSTGRES_PASSWORD=enms
     - POSTGRES_DB=enms
    expose:
      - 5432
    networks:
      - db_network
  enms:
    restart: always
    environment:
     - DATABASE_URL=postgresql://enms:enms@db:5432/enms
     - SECRET_KEY=docker
     - CONFIG_MODE=Production
     - USE_VAULT=0
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - db_network
      - web_network
    depends_on:
      - db
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - enms
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
```

```
db_1     | 2019-09-26 03:36:58.179 UTC [1] LOG:  database system is ready to accept connections
enms_1   | [2019-09-26 03:36:59 +0000] [8] [ERROR] Exception in worker process
enms_1   | Traceback (most recent call last):
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
enms_1   |     cursor, statement, parameters, context
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
enms_1   |     cursor.execute(statement, parameters)
enms_1   | psycopg2.errors.SyntaxError: type modifier is not allowed for type "text"
enms_1   | LINE 4:  device_name TEXT(32768), 
enms_1   |                      ^
enms_1   | The above exception was the direct cause of the following exception:
enms_1   | 
enms_1   | Traceback (most recent call last):
enms_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
enms_1   |     worker.init_process()
enms_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
enms_1   |     self.load_wsgi()
enms_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
enms_1   |     self.wsgi = self.app.wsgi()
enms_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
enms_1   |     self.callable = self.load()
enms_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
enms_1   |     return self.load_wsgiapp()
enms_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
enms_1   |     return util.import_app(self.app_uri)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
enms_1   |     __import__(module)
enms_1   |   File "/app.py", line 1, in <module>
enms_1   |     from eNMS.framework import create_app
enms_1   |   File "/eNMS/__init__.py", line 6, in <module>
enms_1   |     app.configure_database()
enms_1   |   File "/eNMS/controller/base.py", line 243, in configure_database
enms_1   |     Base.metadata.create_all(bind=engine)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4294, in create_all
enms_1   |     ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2046, in _run_visitor
enms_1   |     conn._run_visitor(visitorcallable, element, **kwargs)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1615, in _run_visitor
enms_1   |     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 132, in traverse_single
enms_1   |     return meth(obj, **kw)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 781, in visit_metadata
enms_1   |     _is_metadata_operation=True,
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 132, in traverse_single
enms_1   |     return meth(obj, **kw)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 826, in visit_table
enms_1   |     include_foreign_key_constraints,
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
enms_1   |     return meth(self, multiparams, params)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
enms_1   |     return connection._execute_ddl(self, multiparams, params)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
enms_1   |     compiled,
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
enms_1   |     e, statement, parameters, cursor, context
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
enms_1   |     util.raise_from_cause(sqlalchemy_exception, exc_info)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
enms_1   |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
enms_1   |     raise value.with_traceback(tb)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
enms_1   |     cursor, statement, parameters, context
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
enms_1   |     cursor.execute(statement, parameters)
enms_1   | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) type modifier is not allowed for type "text"
enms_1   | LINE 4:  device_name TEXT(32768), 
enms_1   |                      ^
enms_1   | [SQL: 
enms_1   | CREATE TABLE "AbstractPool" (
enms_1   |      id SERIAL NOT NULL, 
enms_1   |      device_name TEXT(32768), 
enms_1   |      device_description TEXT(32768), 
enms_1   |      device_subtype TEXT(32768), 
enms_1   |      device_model TEXT(32768), 
db_1     | 2019-09-26 03:36:59.224 UTC [65] ERROR:  type modifier is not allowed for type "text" at character 67
db_1     | 2019-09-26 03:36:59.224 UTC [65] STATEMENT:  
db_1     |      CREATE TABLE "AbstractPool" (
db_1     |              id SERIAL NOT NULL, 
db_1     |              device_name TEXT(32768), 
db_1     |              device_description TEXT(32768), 
db_1     |              device_subtype TEXT(32768), 
db_1     |              device_model TEXT(32768), 
db_1     |              device_location TEXT(32768), 
db_1     |              device_vendor TEXT(32768), 
db_1     |              device_icon TEXT(32768), 
```
Could you please help figuring out what is wrong?
